#!/usr/bin/env bash
# test_cursor_adapters.sh — Verify Cursor adapters stay in sync with canonical sources.

set -uo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/helpers.sh"

begin_test "Cursor adapters match workflows and Claude agents"

if output=$(bash "$HEPHAESTUS_ROOT/scripts/sync-cursor-adapters.sh" --check 2>&1); then
  pass "sync-cursor-adapters.sh --check exits 0"
else
  fail "sync-cursor-adapters.sh --check exits non-zero" "$output"
fi

copy_fixture() {
  local dest=$1
  cp -R "$HEPHAESTUS_ROOT/.ai" "$dest/.ai"
  cp -R "$HEPHAESTUS_ROOT/.claude" "$dest/.claude"
  cp -R "$HEPHAESTUS_ROOT/.cursor" "$dest/.cursor"
  mkdir -p "$dest/scripts"
  cp "$HEPHAESTUS_ROOT/scripts/sync-cursor-adapters.sh" "$dest/scripts/sync-cursor-adapters.sh"
  cp "$HEPHAESTUS_ROOT/scripts/models.sh" "$dest/scripts/models.sh"
}

begin_test "Cursor adapter check detects command drift"

FIXTURE=$(mktemp -d "${TMPDIR:-/tmp}/heph-cursor-XXXXXX")
trap 'rm -rf "$FIXTURE"' EXIT

copy_fixture "$FIXTURE"

sed -i.bak 's/Run the full autonomous pipeline/Run the drifted autonomous pipeline/' \
  "$FIXTURE/.cursor/commands/autopilot.md"
rm -f "$FIXTURE/.cursor/commands/autopilot.md.bak"

if drift_output=$(bash "$FIXTURE/scripts/sync-cursor-adapters.sh" --check 2>&1); then
  fail "Cursor adapter check should detect command drift" "exited 0, output: $drift_output"
else
  if echo "$drift_output" | grep -q "Cursor adapter drift for /autopilot"; then
    pass "Cursor adapter check reports /autopilot drift"
  else
    fail "Cursor adapter check failed without naming /autopilot" "$drift_output"
  fi
fi

begin_test "Cursor adapter check detects rule drift"

FIXTURE_RULE=$(mktemp -d "${TMPDIR:-/tmp}/heph-cursor-XXXXXX")
trap 'rm -rf "$FIXTURE" "$FIXTURE_RULE"' EXIT

copy_fixture "$FIXTURE_RULE"

sed -i.bak 's#| /ship | /critique |#| /ship | /nowhere |#' "$FIXTURE_RULE/.cursor/rules/hephaestus.mdc"
rm -f "$FIXTURE_RULE/.cursor/rules/hephaestus.mdc.bak"

if rule_output=$(bash "$FIXTURE_RULE/scripts/sync-cursor-adapters.sh" --check 2>&1); then
  fail "Cursor adapter check should detect rule drift" "exited 0, output: $rule_output"
else
  assert_contains "check names the drifted rule" "$rule_output" "Cursor adapter drift for hephaestus.mdc"
fi

begin_test "Cursor adapter check detects stale adapters after source deletion"

FIXTURE2=$(mktemp -d "${TMPDIR:-/tmp}/heph-cursor-XXXXXX")
trap 'rm -rf "$FIXTURE" "$FIXTURE_RULE" "$FIXTURE2"' EXIT

copy_fixture "$FIXTURE2"

rm "$FIXTURE2/.ai/workflows/research.md"
rm "$FIXTURE2/.claude/agents/tester.md"

if stale_output=$(bash "$FIXTURE2/scripts/sync-cursor-adapters.sh" --check 2>&1); then
  fail "Cursor check should detect orphaned adapters" "exited 0, output: $stale_output"
else
  assert_contains "check names stale command adapter" "$stale_output" ".cursor/commands/research.md"
  assert_contains "check names stale subagent adapter" "$stale_output" ".cursor/agents/tester.md"
fi

sync_output=$(bash "$FIXTURE2/scripts/sync-cursor-adapters.sh" 2>&1)
assert_contains "sync reports stale adapter removal" "$sync_output" "removed stale Cursor adapter"
assert_file_not_exists "sync removes orphaned command adapter" "$FIXTURE2/.cursor/commands/research.md"
assert_file_not_exists "sync removes orphaned subagent adapter" "$FIXTURE2/.cursor/agents/tester.md"

sed -i.bak '/^name:/d' "$FIXTURE2/.claude/agents/coder.md"
bash "$FIXTURE2/scripts/sync-cursor-adapters.sh" >/dev/null 2>&1
assert_exit_code "sync fails on unparseable source" 1 "$?"
assert_file_exists "sync keeps adapter of unparseable source" "$FIXTURE2/.cursor/agents/coder.md"

begin_test "Cursor sync guards hand-written files by directory"

FIXTURE3=$(mktemp -d "${TMPDIR:-/tmp}/heph-cursor-XXXXXX")
trap 'rm -rf "$FIXTURE" "$FIXTURE_RULE" "$FIXTURE2" "$FIXTURE3"' EXIT

copy_fixture "$FIXTURE3"

# .cursor/rules/ is shared with the project's own rules — left alone, no error.
printf -- '---\nalwaysApply: true\n---\nProject rule.\n' > "$FIXTURE3/.cursor/rules/mine.mdc"
# A rule generated by some OTHER tool carries a generic "do not edit directly"
# banner. Deleting it would be silent and unrecoverable, so the ownership marker
# must name one of OUR canonical source dirs, not just any auto-gen banner.
printf -- '---\nalwaysApply: true\n---\n<!-- AUTOGENERATED by my-rulegen; do not edit directly -->\nAPI key policy.\n' \
  > "$FIXTURE3/.cursor/rules/other-tool.mdc"
# .cursor/commands/ is generator-owned — a stray file is reported, never deleted.
printf -- 'Do things.\n' > "$FIXTURE3/.cursor/commands/hand-rolled.md"

if foreign_output=$(bash "$FIXTURE3/scripts/sync-cursor-adapters.sh" 2>&1); then
  fail "sync should exit non-zero on non-generated command file" "exited 0, output: $foreign_output"
else
  assert_contains "sync flags non-generated command" "$foreign_output" "non-generated file"
fi
assert_file_exists "non-generated command preserved" "$FIXTURE3/.cursor/commands/hand-rolled.md"
assert_file_exists "project's own Cursor rule preserved" "$FIXTURE3/.cursor/rules/mine.mdc"
assert_file_exists "another tool's generated rule preserved" "$FIXTURE3/.cursor/rules/other-tool.mdc"
assert_not_contains "project's own rule is not flagged" "$foreign_output" "mine.mdc"

# --check must report the stray too, not only sync mode.
if check_foreign=$(bash "$FIXTURE3/scripts/sync-cursor-adapters.sh" --check 2>&1); then
  fail "--check should exit non-zero on non-generated command file" "exited 0"
else
  assert_contains "--check flags non-generated command" "$check_foreign" "hand-rolled.md"
fi

# A copy of one of OUR adapters under a new name carries the original's marker —
# the natural way to customize a subagent. Identity-scoped ownership means it is
# the project's file, so it is reported, never deleted.
rm "$FIXTURE3/.cursor/commands/hand-rolled.md"
cp "$FIXTURE3/.cursor/rules/hephaestus.mdc" "$FIXTURE3/.cursor/rules/hephaestus-old.mdc"
cp "$FIXTURE3/.cursor/agents/reviewer.md" "$FIXTURE3/.cursor/agents/reviewer-strict.md"
copy_output=$(bash "$FIXTURE3/scripts/sync-cursor-adapters.sh" 2>&1)
assert_file_exists "renamed copy of our rule preserved"     "$FIXTURE3/.cursor/rules/hephaestus-old.mdc"
assert_file_exists "renamed copy of our subagent preserved" "$FIXTURE3/.cursor/agents/reviewer-strict.md"
assert_file_exists "other tool's rule still preserved"      "$FIXTURE3/.cursor/rules/other-tool.mdc"
assert_contains    "renamed subagent copy is reported"      "$copy_output" "reviewer-strict.md"

# A genuinely stale adapter names its OWN, now-missing source — still reclaimed.
rm -f "$FIXTURE3/.cursor/agents/reviewer-strict.md"
sed 's|generated from .claude/agents/reviewer.md|generated from .claude/agents/retired.md|' \
  "$FIXTURE3/.cursor/agents/reviewer.md" > "$FIXTURE3/.cursor/agents/retired.md"
reclaim_output=$(bash "$FIXTURE3/scripts/sync-cursor-adapters.sh" 2>&1)
assert_contains        "sync reclaims a genuinely stale adapter" "$reclaim_output" "removed stale Cursor adapter"
assert_file_not_exists "stale adapter removed"                   "$FIXTURE3/.cursor/agents/retired.md"

begin_test "Cursor commands carry no frontmatter and keep \$ARGUMENTS"

start="$HEPHAESTUS_ROOT/.cursor/commands/start-issue.md"
ship="$HEPHAESTUS_ROOT/.cursor/commands/ship.md"
orient="$HEPHAESTUS_ROOT/.cursor/commands/orient.md"

# Cursor injects .cursor/commands/*.md verbatim — YAML frontmatter would reach
# the model as literal text, so no adapter may carry any.
frontmattered=""
for cmd_file in "$HEPHAESTUS_ROOT"/.cursor/commands/*.md; do
  [ "$(head -1 "$cmd_file")" = "---" ] && frontmattered="$frontmattered $(basename "$cmd_file")"
done
assert_eq "no command opens with frontmatter" "" "$frontmattered"
# Cursor substitutes $ARGUMENTS and $1..$n, so the placeholder must survive.
assert_contains "start-issue keeps \$ARGUMENTS" "$(cat "$start")" '$ARGUMENTS'
# The hover preview is the first non-blank line — it must be the description.
assert_contains "first line is the workflow description" "$(head -1 "$start")" "Start working on issue"
assert_contains "start-issue declares requires" "$(cat "$start")" "<!-- requires: coder, explorer -->"
assert_contains "start-issue names its source" "$(cat "$start")" "generated from .ai/workflows/start-issue.md"
assert_contains "orient is generated too" "$(cat "$orient")" "generated from .ai/workflows/orient.md"

begin_test "Cursor commands use Cursor dialect and chain notes"

refactor="$HEPHAESTUS_ROOT/.cursor/commands/refactor.md"
autopilot="$HEPHAESTUS_ROOT/.cursor/commands/autopilot.md"

assert_contains "start-issue has Cursor callout" "$(cat "$start")" "**Cursor:**"
assert_contains "start-issue chain note names nested cmd" "$(cat "$start")" "/test-issue"
assert_contains "autopilot chain note" "$(cat "$autopilot")" "/start-issue"
assert_contains "orient callout has no chain clause" "$(cat "$orient")" "Delegate to the subagents"
assert_not_contains "orient declares no chains inline" "$(cat "$orient")" "Invoke nested workflows"
assert_contains "start-issue maps the todo tool" "$(cat "$start")" "the to-do list"
assert_not_contains "start-issue drops TodoWrite" "$(cat "$start")" "TodoWrite"
assert_contains "start-issue serializes coder edits" "$(cat "$start")" "Cursor subagents share one working tree"
assert_not_contains "start-issue drops worktree wording" "$(cat "$start")" "coder subagents (in worktrees)"
assert_contains "refactor serializes coder edits" "$(cat "$refactor")" "Cursor subagents share one working tree"

begin_test "Cursor subagents emit only keys Cursor reads"

coder="$HEPHAESTUS_ROOT/.cursor/agents/coder.md"
reviewer="$HEPHAESTUS_ROOT/.cursor/agents/reviewer.md"
researcher="$HEPHAESTUS_ROOT/.cursor/agents/researcher.md"

# Emitting a key Cursor ignores would encode a guarantee nothing enforces.
for agent_file in "$HEPHAESTUS_ROOT"/.cursor/agents/*.md; do
  fm=$(awk '/^---$/ { if (++f == 2) exit; next } f == 1 && !/^#/' "$agent_file")
  unread=$(printf '%s\n' "$fm" | sed -n 's/^\([a-z_-]*\):.*/\1/p' \
    | grep -vE '^(name|description|model|tools|readonly|background|is_background|force-default-model)$' || true)
  assert_eq "$(basename "$agent_file"): no keys Cursor ignores" "" "$unread"
done

# `readonly: true` (permissionMode READONLY) sandboxes the shell to read-only and
# nothing else — measured on Cursor 3.13.21, not inferred. So every role that
# never writes carries it, and only a role whose shell must write is exempt.
assert_contains "researcher is enforced read-only" "$(cat "$researcher")" "readonly: true"
for ro_agent in reviewer explorer; do
  assert_eq "$ro_agent gets a sandboxed shell (readonly)" "1" \
    "$(grep -c '^readonly: true$' "$HEPHAESTUS_ROOT/.cursor/agents/$ro_agent.md")"
  assert_contains "$ro_agent warned the write tool escapes the sandbox" \
    "$(cat "$HEPHAESTUS_ROOT/.cursor/agents/$ro_agent.md")" "bypass the sandbox"
done
# tester is read-only in intent but its shell must write — a sandboxed shell
# fails the test command outright, so `shell: write` exempts it.
assert_eq "tester keeps a writable shell (no readonly)" "0" \
  "$(grep -c '^readonly:' "$HEPHAESTUS_ROOT/.cursor/agents/tester.md")"
assert_contains "tester told not to modify files" \
  "$(cat "$HEPHAESTUS_ROOT/.cursor/agents/tester.md")" "> **Read-only by instruction.**"
assert_eq "coder is not read-only" "0" "$(grep -c '^readonly:' "$coder")"
# Cursor splits on the first ':' without unquoting, so a quoted value would reach
# the model with its quotes attached.
assert_eq "description is unquoted" "0" "$(grep -c '^description: "' "$reviewer")"

assert_contains "coder declares its name" "$(cat "$coder")" "name: coder"
assert_contains "coder description warns orchestrator about isolation" "$(grep '^description:' "$coder")" "NOTE: Cursor has no worktree isolation"
assert_contains "coder body warns about missing worktree isolation" "$(cat "$coder")" "> **No worktree isolation.**"
assert_not_contains "reviewer has no isolation warning" "$(cat "$reviewer")" "No worktree isolation"
assert_not_contains "coder is not told to stay read-only" "$(cat "$coder")" "Read-only"
# No cursor.* defaults ship — tiers inherit the session model until overridden.
assert_eq "no model pinned by default" "0" "$(grep -c '^model:' "$reviewer")"

begin_test "Cursor worktrees command spawns cursor-agent, not claude"

worktrees=$(cat "$HEPHAESTUS_ROOT/.cursor/commands/worktrees.md")
assert_contains "osascript spawn uses cursor-agent" "$worktrees" 'do script "cd <worktree> && cursor-agent \"/start-issue <N>\""'
assert_contains "manual fallback uses cursor-agent" "$worktrees" 'cd <worktree> && cursor-agent "/start-issue <N>"'
assert_contains "summary names Cursor sessions"     "$worktrees" "spawn a seeded Cursor session"

# Repo-wide guard over the two families that must contain no Claude dialect at
# all. Bare "claude" is not a needle: `.claude/` paths are legitimate.
leaks=$(grep -rnF -e "Claude Code" -e "&& claude " -e "claude -" -e "--permission-mode" \
  "$HEPHAESTUS_ROOT/.cursor/commands/" "$HEPHAESTUS_ROOT/.cursor/agents/" 2>/dev/null || true)
assert_eq "no Claude-product leak in any Cursor command or subagent" "" "$leaks"
# The rule names Claude Code on purpose (it explains the mapping), but must never
# carry an executable Claude invocation.
rule_leaks=$(grep -rnF -e "&& claude " -e "claude -" -e "--permission-mode" \
  "$HEPHAESTUS_ROOT/.cursor/rules/" 2>/dev/null || true)
assert_eq "no Claude CLI invocation in the Cursor rule" "" "$rule_leaks"

begin_test "Cursor rule carries the chain graph and harness mapping"

rule="$HEPHAESTUS_ROOT/.cursor/rules/hephaestus.mdc"

assert_contains "rule always applies" "$(cat "$rule")" "alwaysApply: true"
assert_contains "rule names its sources" "$(cat "$rule")" "generated from .ai/workflows/ and .claude/agents/"
assert_contains "rule lists a chain edge" "$(cat "$rule")" "| /ship | /critique |"
assert_contains "rule explains worktree mapping" "$(cat "$rule")" "Subagents, no worktrees."
assert_contains "rule explains verbatim injection" "$(cat "$rule")" "injected verbatim"
# Retry limits live in CLAUDE.md — restating them in an always-apply rule drifts.
assert_contains "rule defers gates to CLAUDE.md" "$(cat "$rule")" "CLAUDE.md"
assert_not_contains "rule does not restate retry limits" "$(cat "$rule")" "max 3 iterations"

print_summary
